/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_ATTRIBUTES_ATTRIBUTES_PB_H_INCLUDED
#define PB_ATTRIBUTES_ATTRIBUTES_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _attributes_SensorConfiguration {
    /* string firmwareVersion = 1; 
string serialNumber = 2; */
    uint32_t intervalo_envio; /* Añadimos esto para que coincida con tu lógica de C */
} attributes_SensorConfiguration;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define attributes_SensorConfiguration_init_default {0}
#define attributes_SensorConfiguration_init_zero {0}

/* Field tags (for use in manual encoding/decoding) */
#define attributes_SensorConfiguration_intervalo_envio_tag 1

/* Struct field encoding specification for nanopb */
#define attributes_SensorConfiguration_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   intervalo_envio,   1)
#define attributes_SensorConfiguration_CALLBACK NULL
#define attributes_SensorConfiguration_DEFAULT NULL

extern const pb_msgdesc_t attributes_SensorConfiguration_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define attributes_SensorConfiguration_fields &attributes_SensorConfiguration_msg

/* Maximum encoded size of messages (where known) */
#define ATTRIBUTES_ATTRIBUTES_PB_H_MAX_SIZE      attributes_SensorConfiguration_size
#define attributes_SensorConfiguration_size      6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
